/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type Link = {
  _type: "link";
  label?: string;
  href?: string;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type WorkPage = {
  _id: string;
  _type: "workPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  intro?: {
    headline?: string;
    description?: string;
  };
  featuredProjects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  cta?: {
    headline?: string;
    description?: string;
    link?: Link;
  };
  seo?: Seo;
};

export type ServicesPage = {
  _id: string;
  _type: "servicesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  intro?: {
    headline?: string;
    description?: string;
    packagesLabel?: string;
    cta?: Link;
  };
  offer?: {
    headline?: string;
    description?: string;
    items?: Array<{
      title?: string;
      description?: string;
      icon?: "design" | "development" | "content";
      _key: string;
    }>;
  };
  packages?: {
    headline?: string;
    description?: string;
    ctaLabel?: string;
    items?: Array<{
      name?: string;
      price?: string;
      blurb?: string;
      features?: Array<string>;
      featured?: boolean;
      _key: string;
    }>;
    note?: string;
    noteLink?: Link;
  };
  finalCta?: {
    headline?: string;
    description?: string;
    link?: Link;
  };
  seo?: Seo;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  link?: string;
  tags?: Array<string>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  hero?: {
    headline?: string;
    intro?: string;
    primaryCta?: Link;
    secondaryCta?: Link;
  };
  about?: {
    headline?: string;
    body?: Array<string>;
    cta?: Link;
    principles?: Array<{
      title?: string;
      summary?: string;
      description?: string;
      _type: "principle";
      _key: string;
    }>;
  };
  services?: {
    headline?: string;
    intro?: string;
    items?: Array<{
      title?: string;
      summary?: string;
      detail?: string;
      tags?: Array<string>;
      _type: "serviceItem";
      _key: string;
    }>;
  };
  portfolio?: {
    headline?: string;
    intro?: string;
    cta?: Link;
    featuredProjects?: Array<
      {
        _key: string;
      } & ProjectReference
    >;
  };
  contact?: {
    headline?: string;
    intro?: string;
    email?: string;
  };
  seo?: Seo;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  intro?: {
    headline?: string;
    description?: string;
  };
  emailSection?: {
    headline?: string;
    description?: string;
    email?: string;
  };
  formSection?: {
    headline?: string;
    description?: string;
  };
  seo?: Seo;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  story?: {
    headline?: string;
    body?: Array<string>;
  };
  cta?: {
    headline?: string;
    intro?: string;
    link?: Link;
  };
  seo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Seo
  | Link
  | ProjectReference
  | WorkPage
  | ServicesPage
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | HomePage
  | ContactPage
  | AboutPage
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_id == "contactPage"][0]{    title,    intro{ headline, description },    emailSection{ headline, description, email },    formSection{ headline, description },    seo{      title,      description,      image,      noIndex    }  }
export type CONTACT_PAGE_QUERY_RESULT =
  | {
      title: string | null;
      intro: null;
      emailSection: null;
      formSection: null;
      seo: null;
    }
  | {
      title: string | null;
      intro: null;
      emailSection: null;
      formSection: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex: boolean | null;
      } | null;
    }
  | {
      title: string | null;
      intro: {
        headline: string | null;
        description: string | null;
      } | null;
      emailSection: null;
      formSection: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex: boolean | null;
      } | null;
    }
  | {
      title: string | null;
      intro: {
        headline: string | null;
        description: string | null;
      } | null;
      emailSection: {
        headline: string | null;
        description: string | null;
        email: string | null;
      } | null;
      formSection: {
        headline: string | null;
        description: string | null;
      } | null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex: boolean | null;
      } | null;
    }
  | null;

// Source: src/sanity/lib/queries.ts
// Variable: WORK_PAGE_QUERY
// Query: *[_id == "workPage"][0]{    title,    intro{ headline, description },    featuredProjects[]->{ _id, title, description, "href": link, "image": image.asset->url, tags },    cta{ headline, description, link{ label, href } },    seo{      title,      description,      image,      noIndex    }  }
export type WORK_PAGE_QUERY_RESULT =
  | {
      title: string | null;
      intro: null;
      featuredProjects: null;
      cta: null;
      seo: null;
    }
  | {
      title: string | null;
      intro: null;
      featuredProjects: null;
      cta: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex: boolean | null;
      } | null;
    }
  | {
      title: string | null;
      intro: {
        headline: string | null;
        description: string | null;
      } | null;
      featuredProjects: null;
      cta: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex: boolean | null;
      } | null;
    }
  | {
      title: string | null;
      intro: null;
      featuredProjects: null;
      cta: {
        headline: string | null;
        description: null;
        link: {
          label: string | null;
          href: string | null;
        } | null;
      } | null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex: boolean | null;
      } | null;
    }
  | {
      title: string | null;
      intro: {
        headline: string | null;
        description: string | null;
      } | null;
      featuredProjects: Array<{
        _id: string;
        title: string | null;
        description: string | null;
        href: string | null;
        image: string | null;
        tags: Array<string> | null;
      }> | null;
      cta: {
        headline: string | null;
        description: string | null;
        link: {
          label: string | null;
          href: string | null;
        } | null;
      } | null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex: boolean | null;
      } | null;
    }
  | null;

// Source: src/sanity/lib/queries.ts
// Variable: SERVICES_PAGE_QUERY
// Query: *[_id == "servicesPage"][0]{    title,    intro{ headline, description, packagesLabel, cta{ label, href } },    offer{ headline, description, items[]{ _key, title, description, icon } },    packages{ headline, description, ctaLabel, items[]{ _key, name, price, blurb, features, featured }, note, noteLink{ label, href } },    finalCta{ headline, description, link{ label, href } },    seo{      title,      description,      image,      noIndex    }  }
export type SERVICES_PAGE_QUERY_RESULT =
  | {
      title: string | null;
      intro: null;
      offer: null;
      packages: null;
      finalCta: null;
      seo: null;
    }
  | {
      title: string | null;
      intro: null;
      offer: null;
      packages: null;
      finalCta: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex: boolean | null;
      } | null;
    }
  | {
      title: string | null;
      intro: {
        headline: string | null;
        description: string | null;
        packagesLabel: null;
        cta: null;
      } | null;
      offer: null;
      packages: null;
      finalCta: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex: boolean | null;
      } | null;
    }
  | {
      title: string | null;
      intro: {
        headline: string | null;
        description: string | null;
        packagesLabel: string | null;
        cta: {
          label: string | null;
          href: string | null;
        } | null;
      } | null;
      offer: {
        headline: string | null;
        description: string | null;
        items: Array<{
          _key: string;
          title: string | null;
          description: string | null;
          icon: "content" | "design" | "development" | null;
        }> | null;
      } | null;
      packages: {
        headline: string | null;
        description: string | null;
        ctaLabel: string | null;
        items: Array<{
          _key: string;
          name: string | null;
          price: string | null;
          blurb: string | null;
          features: Array<string> | null;
          featured: boolean | null;
        }> | null;
        note: string | null;
        noteLink: {
          label: string | null;
          href: string | null;
        } | null;
      } | null;
      finalCta: {
        headline: string | null;
        description: string | null;
        link: {
          label: string | null;
          href: string | null;
        } | null;
      } | null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex: boolean | null;
      } | null;
    }
  | null;

// Source: src/sanity/lib/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_id == "aboutPage"][0]{    title,    story{      headline,      body    },    cta{      headline,      intro,      link{ label, href }    },    seo{      title,      description,      image,      noIndex    }  }
export type ABOUT_PAGE_QUERY_RESULT =
  | {
      title: string | null;
      story: null;
      cta: null;
      seo: null;
    }
  | {
      title: string | null;
      story: null;
      cta: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex: boolean | null;
      } | null;
    }
  | {
      title: string | null;
      story: null;
      cta: {
        headline: string | null;
        intro: null;
        link: {
          label: string | null;
          href: string | null;
        } | null;
      } | null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex: boolean | null;
      } | null;
    }
  | {
      title: string | null;
      story: {
        headline: string | null;
        body: Array<string> | null;
      } | null;
      cta: {
        headline: string | null;
        intro: string | null;
        link: {
          label: string | null;
          href: string | null;
        } | null;
      } | null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex: boolean | null;
      } | null;
    }
  | null;

// Source: src/sanity/lib/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_id == "homePage"][0]{    title,    hero{      headline,      intro,      primaryCta{ label, href },      secondaryCta{ label, href }    },    about{      headline,      body,      cta{ label, href },      principles[]{        _key,        title,        summary,        description      }    },    services{      headline,      intro,      items[]{        _key,        title,        summary,        detail,        tags      }    },    portfolio{      headline,      intro,      cta{ label, href },      featuredProjects[]->{        _id,        title,        description,        "href": link,        "image": image.asset->url,        tags      }    },    contact{      headline,      intro,      email    },    seo{      title,      description,      image,      noIndex    }  }
export type HOME_PAGE_QUERY_RESULT =
  | {
      title: string | null;
      hero: null;
      about: null;
      services: null;
      portfolio: null;
      contact: null;
      seo: null;
    }
  | {
      title: string | null;
      hero: null;
      about: null;
      services: null;
      portfolio: null;
      contact: null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex: boolean | null;
      } | null;
    }
  | {
      title: string | null;
      hero: {
        headline: string | null;
        intro: string | null;
        primaryCta: {
          label: string | null;
          href: string | null;
        } | null;
        secondaryCta: {
          label: string | null;
          href: string | null;
        } | null;
      } | null;
      about: {
        headline: string | null;
        body: Array<string> | null;
        cta: {
          label: string | null;
          href: string | null;
        } | null;
        principles: Array<{
          _key: string;
          title: string | null;
          summary: string | null;
          description: string | null;
        }> | null;
      } | null;
      services: {
        headline: string | null;
        intro: string | null;
        items: Array<{
          _key: string;
          title: string | null;
          summary: string | null;
          detail: string | null;
          tags: Array<string> | null;
        }> | null;
      } | null;
      portfolio: {
        headline: string | null;
        intro: string | null;
        cta: {
          label: string | null;
          href: string | null;
        } | null;
        featuredProjects: Array<{
          _id: string;
          title: string | null;
          description: string | null;
          href: string | null;
          image: string | null;
          tags: Array<string> | null;
        }> | null;
      } | null;
      contact: {
        headline: string | null;
        intro: string | null;
        email: string | null;
      } | null;
      seo: {
        title: string | null;
        description: string | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        noIndex: boolean | null;
      } | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "contactPage"][0]{\n    title,\n    intro{ headline, description },\n    emailSection{ headline, description, email },\n    formSection{ headline, description },\n    seo{\n      title,\n      description,\n      image,\n      noIndex\n    }\n  }\n': CONTACT_PAGE_QUERY_RESULT;
    '\n  *[_id == "workPage"][0]{\n    title,\n    intro{ headline, description },\n    featuredProjects[]->{ _id, title, description, "href": link, "image": image.asset->url, tags },\n    cta{ headline, description, link{ label, href } },\n    seo{\n      title,\n      description,\n      image,\n      noIndex\n    }\n  }\n': WORK_PAGE_QUERY_RESULT;
    '\n  *[_id == "servicesPage"][0]{\n    title,\n    intro{ headline, description, packagesLabel, cta{ label, href } },\n    offer{ headline, description, items[]{ _key, title, description, icon } },\n    packages{ headline, description, ctaLabel, items[]{ _key, name, price, blurb, features, featured }, note, noteLink{ label, href } },\n    finalCta{ headline, description, link{ label, href } },\n    seo{\n      title,\n      description,\n      image,\n      noIndex\n    }\n  }\n': SERVICES_PAGE_QUERY_RESULT;
    '\n  *[_id == "aboutPage"][0]{\n    title,\n    story{\n      headline,\n      body\n    },\n    cta{\n      headline,\n      intro,\n      link{ label, href }\n    },\n    seo{\n      title,\n      description,\n      image,\n      noIndex\n    }\n  }\n': ABOUT_PAGE_QUERY_RESULT;
    '\n  *[_id == "homePage"][0]{\n    title,\n    hero{\n      headline,\n      intro,\n      primaryCta{ label, href },\n      secondaryCta{ label, href }\n    },\n    about{\n      headline,\n      body,\n      cta{ label, href },\n      principles[]{\n        _key,\n        title,\n        summary,\n        description\n      }\n    },\n    services{\n      headline,\n      intro,\n      items[]{\n        _key,\n        title,\n        summary,\n        detail,\n        tags\n      }\n    },\n    portfolio{\n      headline,\n      intro,\n      cta{ label, href },\n      featuredProjects[]->{\n        _id,\n        title,\n        description,\n        "href": link,\n        "image": image.asset->url,\n        tags\n      }\n    },\n    contact{\n      headline,\n      intro,\n      email\n    },\n    seo{\n      title,\n      description,\n      image,\n      noIndex\n    }\n  }\n': HOME_PAGE_QUERY_RESULT;
  }
}
